query {
  repository(owner:"networkx", name:"networkx") {
    dependencyGraphManifests(first:100) {
      edges {
        node {
          dependenciesCount
          blobPath
          filename
          parseable
        }
      }
    }
  }
}
